name: Flow Coverage Report

on:
  pull_request:
    paths: ["src/*.js", "!src/setupProxy.js"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: "2"

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34

    - name: Install modules
      run: |
        yarn install

    - name: Run flow coverage on changed files
      run: |
        coverage_report=""
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if [[ $file != "src/setupProxy.js" &&  $file == *.js ]]; then
            # setupProxy.js is not covered by flow.
            coverage_report=$coverage_report"**$file**$(yarn flow coverage --quiet $file | grep -o ": .*")<br />"
          fi
        done
        echo "COVERAGE_REPORT=$coverage_report" >> $GITHUB_ENV
    
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1.5.0
      if: ${{ env.COVERAGE_REPORT != '' }}
      with:
        message: |
          Flow Coverage Report
          -----
          ${{ env.COVERAGE_REPORT }}
        comment_includes: 'Flow Coverage Report'
